// --------------------------------------------------------------------------------------------------------------------
// <copyright company="" file="Settings.Designer.cs">
//   
// </copyright>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <summary>
//   The settings.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Runtime.CompilerServices;

namespace SimpleAR.Properties
{
    /// <summary>
    /// The settings.
    /// </summary>
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase
    {
        /// <summary>
        /// The default instance.
        /// </summary>
        private static Settings defaultInstance = (Settings)(Synchronized(new Settings()));

        /// <summary>
        /// Gets the default.
        /// </summary>
        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
    }
}
